version: '3'

services:
  ap:
    build:
      context: ./build/AP
#    expose: # 本番用
#      - '5000' # 本番用
    ports: # アプリ作成時の試行錯誤用
      - "8000:8000" # アプリ作成時の試行錯誤用
    depends_on:
      - datadbmaster
    volumes:
      - ./static:/static
      - ./build/AP/project:/DJANGO_PROJECT # アプリ作成時の試行錯誤用
    environment:
      WSGI_PORT: 5000                              # WSGIを動かすポート
      WSGI_PROCESSES: 5                    # WSGIを動かすプロセス数
      WSGI_THREADS: 3                        # WSGIを動かすスレッド数
      NGINX_LOCATION_SUBDIR: NGINX_DIR      # Webアクセスするサブディレクトリ名
      DJANGO_DEBUG: 'True'                        # DjangoのDEBUGモードの有効化
      DJANGO_ALLOWED_HOSTS: '*'        # Djangoに接続を許可するホスト名またはIP
      DJANGO_PROJECT_NAME: DJANGO_PROJECT          # Djangoプロジェクトの名前（フォルダ名と合わせる）
      DJANGO_APPLICATION_NAME: todo_app  # Djangoアプリケーションの名前（フォルダ名と合わせる）
      DJANGO_ADMIN_EMAIL: admin@localhost.com            # Django管理者ユーザのEMAIL
      DJANGO_ADMIN_PASSWORD: djangoadmin      # Django管理者ユーザのパスワード
      DATABASE_CONTAINER_NAME: datadbmaster  # Djangoで使用するDBコンテナの名前
      DATABASE_PORT: 3306                      # Djangoで使用するDBコンテナの公開ポート
      MYSQL_DATABASE: datadb                    # Djangoで使用するDBの名前
      MYSQL_USER: datadbuser                            # Djangoで使用するDBのログインユーザ
      MYSQL_PASSWORD: datadbpassword                    # Djangoで使用するDBのログインパスワード
      CACHE_CONTAINER_NAME: cache  # Djangoで使用するCACHEコンテナの名前
      CACHE_PORT: 11211                      # Djangoで使用するCACHEコンテナの公開ポート


  datadbmaster:
    build: ./build/datadb
    expose: # 本番用
      - '3306' # 本番用
#    ports: # アプリ作成時の試行錯誤用
#      - "3306:3306" # アプリ作成時の試行錯誤用
    environment:
      - MYSQL_MASTER=true
      - MYSQL_ROOT_PASSWORD=datadbroot
      - MYSQL_DATABASE=datadb
      - MYSQL_USER=datadbuser
      - MYSQL_PASSWORD=datadbpassword
      - TZ=Asia/Tokyo
    depends_on:
      - cache
    volumes:
      - ./datadb:/var/lib/mysql

      
  cache:
    image: memcached:alpine
    expose:
      - '11211'

      